### ISSUE TITLE
Python 2.7.5 support?

### ISSUE THREAD

**Issue by pejacobysbs** [tenable/audit_scripts#10]
We tried running the script on our Tenable.sc v5.7.1 on-prem host, which has Python 2.7.5 installed.  Changed the #! line to '#!/usr/bin/env python' and we get a syntax error:

```
  File "./create_baseline_audit.py", line 89
    print(message, file=out)
                       ^
SyntaxError: invalid syntax
```

I'm not a python coder, so just curious if this is something simple to address to allow the script to run on older python versions. Or can we install python3 on the host without impacting Tenable.sc functions.

**Comment by streckc** [comment]
The file parameter is specific to python3.  I will look into changing the messages to file writes, which can be more transportable.

Installing python3 on the host _should_ not affect the operation of Tenable.sc, as one would call `python`, and the other `python3`.  But I do not have the data to prove that out.

**Comment by streckc** [comment]
One other tip... you do not have to change the `#!` line if you call python directly:
`python ./create_baseline_audit.py`

**Comment by streckc** [comment]
If you pull the updated code, it should work in python 2 now.

**Comment by pejacobysbs** [comment]
Confirmed this works under Python 2.75 
  Python 2.7.5 (default, Sep 12 2018, 05:31:16)
  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2

Thanks!
