### ISSUE TITLE
Parse error with generated Audit file

### ISSUE THREAD

**Issue by ashw2002** [tenable/audit_scripts#31]
Recently I've been having issues with with the audit files that this script generated.  If I export a scan from Nessus Pro and use it with the Red Hat EL 8 v2 L1 audit file, the resulting file will give me a parsing error with the following Text: 

"Parse error line 771 - unknown token ‘$grubdir/user.cfg\\“\”;’Could not parse the file 73c86e31-9a1f-54bc-949a-16cae5563d66-54093435-scfile_6zxUFn". 

 Additionally, The specified line does not line up with where the actual problem lies.  I have done some digging and it appears that this may be an error with the escape characters within the file.  In the provided example, I need to add an additional '\' to the two on the tail end of the unknown token '$grubdir/user.cfg\\\“\”;’  .    Adding this additional backslash will allow the script to continue further on.

Thank you very much for your help

**Comment by streckc** [comment]
@ashw2002 Would you give this version a test?
https://github.com/tenable/audit_scripts/blob/issue31_quoted_parse_error/db_audit_migrate/db_audit_migrate.py

I have it so it is creating parsable files, but would like to get a real world test on if it provides the proper values.  If it looks good, I can merge to master.

**Comment by ashw2002** [comment]
@streckc While attempting to use this new branch on our audit files and it is telling me that neither my nessus export, nor my audit file exported from the audit portal is supported. I am using the CIS_Red_Hat_EL8_Server_v2.0.0_L1.audit exported from [audits.tar.gz](https://www.tenable.com/downloads/download-all-compliance-audit-files).  Any advice on what may be causing this?  As far as I can tell: read_audit_lines is returning none, but my python is a bit rusty.  Thank you very much.

**Comment by ashw2002** [comment]
@streckc, I have discovered where the error lies in the audit file.   When line 125 of the audit file '<check_type:"Unix" >' is passed through the db_type_re.search(line) on line 161 of the script, it returns a null and  then returns out of the read_audit_lines() function, determining that the audit is not supported.  I hope this helps

**Comment by streckc** [comment]
Can you verify the command you are running is testing `baseline/create_baseline_audit.py`? It feels like you may be trying to use the `db_audit_migrate.py` script.

Actually... I see where it went bad... I was mixed up in my prior comment.  Please test with that branch, but the `baseline/create_baseline_audit.py` script.

My apologies.

**Comment by ashw2002** [comment]
@streckc, Yes, That appeared to be the issue. I grabbed the new version from that branch and the audit file runs well.  I am getting the same results using both the original Audit file and the newly generated one.  I'll be comparing them and looking into this in further detail to see if I can figure out why this is.
Thank you very much for your help.

**Comment by ashw2002** [comment]
@streckc.  I have tested this script on Windows Server 2022 benchmarks as well as Red Hat EL 8.  I have the results, as well as the generated audit files if you want to take a look at them.  I am still not entirely sure why we get detections after using the generated audit files.  Is there a way for me to securely send these files to you?  I am worried that the known good values may have sensitive data in them and am unwilling to upload them to a public repository.
Thank you very much for your help

**Comment by ijwood** [comment]
[example.csv](https://github.com/tenable/audit_scripts/files/11249276/example.csv)

Hi,
We have the same problem so I tried using the new test version of the script and it doesn't quite work as expected. It does parse correctly now but produces a lot of failures. I scanned a sample RHEL8 server with the original CIS benchmark then ran the output through the script to create a new Audit file. I then scanned the same server with the new Audit file but the new file reported 102 failures (the original scan only reported 43). I've attached a sample of the output from one of the failures in case it's helpful. We have a test server with no sensitive data on it so I can provide other info/files if you need them.
Thank you for your efforts on this.

**Comment by streckc** [comment]
@ijwood Script may need some work to normalize values a bit better.  The difference in that failure is escaping in the lines that start with `+` and `-`.  I'll explore a bit more if I can reproduce it.

@ashw2002 I got lost in some busy work and will try to re-engage in exploring the issue.

**Comment by ijwood** [comment]
@streckc Thanks you for looking into it.  If you need any more real-world examples, just let me know.

**Comment by streckc** [comment]
I'm sorry I went dark on this, but the reasoning is the feature is being brought into the product, and can be supported via Tenable Support: https://community.tenable.com/s/feed/0D53a00009Knr17CAB
