### ISSUE TITLE
Applying values issue

### ISSUE THREAD

**Issue by pnancarrow** [tenable/audit_scripts#8]
I am getting the following issue when the baseline script starts applying values:

```
Applying values
Applying values for _xx.xx.xx.xx_

The command '/bin/grep -E '^[\s]*install cramfs /bin/true' /etc/modprobe.d/* |/usr/bin/awk '{print} END {if (NR != 0) print "pass" ; else print "fail"}'' returned :

/etc/modprobe.d/CIS.conf:install cramfs /bin/true
pass
```

**Comment by streckc** [comment]
That could be challenging.  The issue is due to both single and double quotes being in the value.  I'll see if I can reproduce and fix.

**Comment by pnancarrow** [comment]
Thanks. It's based off of a CIS Ubuntu 16.04 scan if that is helpful. @streckc

**Comment by streckc** [comment]
Fix should be in place.
